import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProviders from "@/redux/providers";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "../config/auth";
import Providers from "@/components/layouts/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader showSpinner={false} />
        <ReduxProviders>
          <Providers session={session}>
            <Toaster />
            {children}
          </Providers>
        </ReduxProviders>
      </body>
    </html>
  );
}
